/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopshirishRouteImport } from './routes/topshirish'
import { Route as IndexRouteImport } from './routes/index'

const TopshirishRoute = TopshirishRouteImport.update({
  id: '/topshirish',
  path: '/topshirish',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/topshirish': typeof TopshirishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/topshirish': typeof TopshirishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/topshirish': typeof TopshirishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/topshirish'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/topshirish'
  id: '__root__' | '/' | '/topshirish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TopshirishRoute: typeof TopshirishRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topshirish': {
      id: '/topshirish'
      path: '/topshirish'
      fullPath: '/topshirish'
      preLoaderRoute: typeof TopshirishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TopshirishRoute: TopshirishRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
